// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchemaHunter.InfrastructureRegistry.Persistence;

#nullable disable

namespace SchemaHunter.InfrastructureRegistry.Persistence.Migrations
{
    [DbContext(typeof(InfrastructureDbContext))]
    [Migration("20260920205231_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchemaHunter.InfrastructureRegistry.Persistence.Entities.AssetCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_asset_categories_code_unique");

                    b.ToTable("asset_categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ROAD",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Highways, regional roads, urban streets.",
                            IsDeleted = false,
                            Name = "Road Infrastructure"
                        },
                        new
                        {
                            Id = 2,
                            Code = "BLDG",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Residential, educational, medical, administrative buildings.",
                            IsDeleted = false,
                            Name = "Building"
                        },
                        new
                        {
                            Id = 3,
                            Code = "BRDG",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Road and railway bridges, pedestrian crossings.",
                            IsDeleted = false,
                            Name = "Bridge"
                        },
                        new
                        {
                            Id = 4,
                            Code = "ENERGY",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Power stations, substations, transmission lines.",
                            IsDeleted = false,
                            Name = "Energy Infrastructure"
                        },
                        new
                        {
                            Id = 5,
                            Code = "WATER",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Water treatment plants, pipelines, pump stations.",
                            IsDeleted = false,
                            Name = "Water Supply"
                        });
                });

            modelBuilder.Entity("SchemaHunter.InfrastructureRegistry.Persistence.Entities.ClassificationTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("label");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_classification_tags_code_unique");

                    b.ToTable("classification_tags", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "PRIORITY",
                            IsDeleted = false,
                            Label = "Priority Project"
                        },
                        new
                        {
                            Id = 2,
                            Code = "DONOR_FUNDED",
                            IsDeleted = false,
                            Label = "Donor Funded"
                        },
                        new
                        {
                            Id = 3,
                            Code = "UNESCO_LISTED",
                            IsDeleted = false,
                            Label = "UNESCO Listed Site"
                        },
                        new
                        {
                            Id = 4,
                            Code = "CRITICAL_INFRA",
                            IsDeleted = false,
                            Label = "Critical Infrastructure"
                        });
                });

            modelBuilder.Entity("SchemaHunter.InfrastructureRegistry.Persistence.Entities.FundingSource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AllocatedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("allocated_amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasDefaultValue("UAH")
                        .HasColumnName("currency_code");

                    b.Property<string>("FundType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fund_type");

                    b.Property<string>("FunderName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("funder_name");

                    b.Property<string>("GrantAgreementNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("grant_agreement_number");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.HasKey("Id");

                    b.HasIndex("FundType")
                        .HasDatabaseName("ix_funding_sources_fund_type");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_funding_sources_project_id");

                    b.ToTable("funding_sources", (string)null);
                });

            modelBuilder.Entity("SchemaHunter.InfrastructureRegistry.Persistence.Entities.ProjectClassificationTag", b =>
                {
                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<int>("TagId")
                        .HasColumnType("int")
                        .HasColumnName("tag_id");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("ProjectId", "TagId");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_pct_tag_id");

                    b.ToTable("project_classification_tags", (string)null);
                });

            modelBuilder.Entity("SchemaHunter.InfrastructureRegistry.Persistence.Entities.ProjectPassport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly?>("ActualCompletionDate")
                        .HasColumnType("date")
                        .HasColumnName("actual_completion_date");

                    b.Property<decimal?>("BuiltAreaSqm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("built_area_sqm");

                    b.Property<DateOnly?>("ConstructionStartDate")
                        .HasColumnType("date")
                        .HasColumnName("construction_start_date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("EdessrNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("edessr_number");

                    b.Property<DateOnly?>("EstimatedCompletionDate")
                        .HasColumnType("date")
                        .HasColumnName("estimated_completion_date");

                    b.Property<decimal?>("GpsLatitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("gps_latitude");

                    b.Property<decimal?>("GpsLongitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("gps_longitude");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("TechnicalPermitNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("technical_permit_number");

                    b.HasKey("Id");

                    b.HasIndex("EdessrNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_project_passports_edessr_number_unique")
                        .HasFilter("[edessr_number] IS NOT NULL");

                    b.HasIndex("ProjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_project_passports_project_id_unique");

                    b.ToTable("project_passports", (string)null);
                });

            modelBuilder.Entity("SchemaHunter.InfrastructureRegistry.Persistence.Entities.ReconstructionProject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AllocatedBudget")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("allocated_budget");

                    b.Property<int>("AssetCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("asset_category_id");

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("asset_code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("name");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("region");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("AssetCategoryId")
                        .HasDatabaseName("ix_reconstruction_projects_category_id");

                    b.HasIndex("AssetCode")
                        .IsUnique()
                        .HasDatabaseName("ix_reconstruction_projects_asset_code_unique");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_reconstruction_projects_status");

                    b.ToTable("reconstruction_projects", (string)null);
                });

            modelBuilder.Entity("SchemaHunter.InfrastructureRegistry.Persistence.Entities.FundingSource", b =>
                {
                    b.HasOne("SchemaHunter.InfrastructureRegistry.Persistence.Entities.ReconstructionProject", "Project")
                        .WithMany("FundingSources")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_funding_sources_project");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SchemaHunter.InfrastructureRegistry.Persistence.Entities.ProjectClassificationTag", b =>
                {
                    b.HasOne("SchemaHunter.InfrastructureRegistry.Persistence.Entities.ReconstructionProject", "Project")
                        .WithMany("ProjectClassificationTags")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pct_project");

                    b.HasOne("SchemaHunter.InfrastructureRegistry.Persistence.Entities.ClassificationTag", "Tag")
                        .WithMany("ProjectClassificationTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pct_tag");

                    b.Navigation("Project");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("SchemaHunter.InfrastructureRegistry.Persistence.Entities.ProjectPassport", b =>
                {
                    b.HasOne("SchemaHunter.InfrastructureRegistry.Persistence.Entities.ReconstructionProject", "Project")
                        .WithOne("Passport")
                        .HasForeignKey("SchemaHunter.InfrastructureRegistry.Persistence.Entities.ProjectPassport", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_passports_project");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SchemaHunter.InfrastructureRegistry.Persistence.Entities.ReconstructionProject", b =>
                {
                    b.HasOne("SchemaHunter.InfrastructureRegistry.Persistence.Entities.AssetCategory", "AssetCategory")
                        .WithMany("Projects")
                        .HasForeignKey("AssetCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reconstruction_projects_asset_category");

                    b.Navigation("AssetCategory");
                });

            modelBuilder.Entity("SchemaHunter.InfrastructureRegistry.Persistence.Entities.AssetCategory", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("SchemaHunter.InfrastructureRegistry.Persistence.Entities.ClassificationTag", b =>
                {
                    b.Navigation("ProjectClassificationTags");
                });

            modelBuilder.Entity("SchemaHunter.InfrastructureRegistry.Persistence.Entities.ReconstructionProject", b =>
                {
                    b.Navigation("FundingSources");

                    b.Navigation("Passport");

                    b.Navigation("ProjectClassificationTags");
                });
#pragma warning restore 612, 618
        }
    }
}
